change direction when bump occurs
ArcQ/sphere-or-cube pull request #3
Opened 2018-09-16 22:56 UTC by eltonlaw

2018-09-29 21:40 UTC, ArcQ requested changes

2018-09-29 21:40 UTC, ArcQ commented on firmware/wheel.ino
> +        delay(20);
how come the delays are so arbitrary between 20 100 and 1000? are they actaully becaus they're diff types of pins? does it make sense to map them to some shared constants? or is it less performant

2018-09-29 22:47 UTC, eltonlaw commented
wheel.ino was deleted in commit 342198a

2018-10-04 05:49 UTC, ArcQ approved these changes

2025-10-27 13:41 UTC, closed without merging